Repository Nomad-Study/nomadstudy-github-list, pull requests merged in 2022-07, with the labels that each got.

#4 Update README.md
  README.md
Labels: Add New

#8 Add User | @Heyyyin
  README.md
Labels: Add New

#10 Add member @DevXLNT
  README.md
Labels: Add New

#12 Revise add_user and update_user in ISSUE_TAMPLATE
  .github/ISSUE_TEMPLATE/add_new_member.md
  .github/ISSUE_TEMPLATE/update_member.md
Labels: bug

#14 Update README.md
  README.md
Labels: Add New

#15 Release 0.4.0
  README.md
Labels: bug, Add New

#17 Update README.md
  README.md
Labels: Add New

#19 Update README.md
  README.md
Labels: Add New

#20 Add User @YeeunKo
  README.md
Labels: Add New

#24 Update README.md
  README.md
Labels: Add New

#25 Hot Fix: Remove blank line
  README.md
Labels: bug

#26 Hotfix 0.8.1
  README.md
Labels: bug

#31 Add User @beyondthedream
  README.md
Labels: Add New

#39 Add User @K-AVLB #35
  README.md
Labels: Add New

#40 Add @juninjune #38
  README.md
Labels: Add New

#41 Add User @overscrap #36
  README.md
Labels: Add New

#42 Release 0.14.0
  README.md
Labels: Add New
